spring:
  application:
    name: eurekaserver-slave
server:
  port: 2222
eureka:
  environment: 测试环境
  datacenter: 测试Eureka服务注册中心(slave)
  server:
    enable-self-preservation: false

  client:
    # 声明是否将自己的信息注册到 Eureka 服务器上
    register-with-eureka: true
    # 是否到 Eureka 服务器中抓取注册信息
    fetch-registry: true
    region: beijing
    availability-zones:
      beijing: zone-1,zone-2
    service-url:
      zone-1: http://eurekaserver-master:1111/eureka/
      zone-2: http://eurekaserver-slave:2222/eureka/
      defaultZone: http://eurekaserver-master:1111/eureka/,http://eurekaserver-slave:${server.port}/eureka/
  instance:
    appname: eurekaserver-slave
    eviction-interval-timer-in-ms: 50000
    lease-renewal-interval-in-secs: 5
    lease-expiration-duration-in-secs: 10
    hostname: eurekaserver-slave
    instance-id: eurekaserver-slave:${server.port}