spring:
  application:
    name: UserService
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.159.128:3306/test?serverTimezone=UTC &useUnicode=true& characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 10001
#mybatis mapper\u6587\u4EF6\u7684\u4F4D\u7F6E
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  #\u626B\u63CFpojo\u7C7B\u7684\u4F4D\u7F6E,\u5728\u6B64\u5904\u6307\u660E\u626B\u63CF\u5B9E\u4F53\u7C7B\u7684\u5305\uFF0C\u5728mapper\u4E2D\u5C31\u53EF\u4EE5\u4E0D\u7528\u5199pojo\u7C7B\u7684\u5168\u8DEF\u5F84\u540D\u4E86
  type-aliases-package: com.baorant.userservice.entity
eureka:
  client:
    service-url:
      defaultZone: http://192.168.159.128:1111/eureka/,http:// 192.168.159.128:2222/eureka/
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}


# 配置日志路径
logging:
  file:
    name: /var/log/user-service/app.log
  level:
    root: debug

