# 服务器配置
server:
  port: 9006
# Spring相关配置
spring:
  # 应用名称配置
  application:
    name: springcloud-config-server
  # RabbitMQ消息中间件配置
  rabbitmq:
    host: 192.168.141.128
    port: 5672
    username: admin
    password: admin
  # Spring Cloud相关配置
  cloud:
    # Spring Cloud Bus配置，用于配置刷新和消息总线
    bus:
      trace:
        enabled: true
    # 配置中心服务端配置
    config:
      server:
        # Git仓库配置，用于从远程Git仓库获取配置文件
        git:
          uri: https://gitee.com/zck1/spring-cloud-demo.git
          search-paths: config # 配置文件所在路径
          username: 1876990651@qq.com
          password: Zckljz0926..
          clone-on-start: true # 启动时是否克隆仓库
          skip-ssl-validation: true # 跳过SSL验证
          default-label: main
# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    busrefresh:
      enabled: true

# 配置日志路径
# 日志配置
logging:
  file:
    name: ./logs/config-server-git.log
  level:
    root: info
    org.springframework.cloud: debug