spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://UserService
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
server:
  port: 4444

eureka:
  client:
    service-url:
      defaultZone: http://192.168.141.128:1111/eureka/,http://192.168.141.128:2222/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# 自定义白名单过滤配置
filter:
  ip:
    whitelist: 192.168.141.1,127.0.0.1
    whitelistenabled: true  # 如果为 TRUE，不在白名单的机器无法访问

# 日志配置
logging:
  file:
    name: /var/log/api-gateway/app.log
  level:
    root: INFO
