spring:
  application:
    # 应用名称，用于服务注册与发现
    name: Api-Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # 用户服务路由配置
            - id: user-service
              # 路由目标URI，lb表示使用负载均衡，UserService是目标服务名
              uri: lb://UserService
              # 路由断言，匹配/users/**路径的请求
              predicates:
                - Path=/users/**
              # 路由过滤器，StripPrefix=1表示转发请求时去除第一层路径前缀
              filters:
                - StripPrefix=1
server:
  # 服务端口
  port: 4444

eureka:
  client:
    service-url:
      # Eureka服务注册中心地址
      defaultZone: http://192.168.141.128:1111/eureka/,http://192.168.141.128:2222/eureka/
    # 是否从Eureka Server获取注册信息
    fetch-registry: true
    # 是否将自身注册到Eureka Server
    register-with-eureka: true
  instance:
    # 注册服务时使用IP地址而不是主机名
    prefer-ip-address: true

# 自定义白名单过滤配置
filter:
  ip:
    # 允许访问的IP白名单列表
    whitelist: 192.168.141.1,127.0.0.1
    # 是否启用白名单功能，如果为true，不在白名单的机器无法访问
    whitelistenabled: true

# 日志配置
logging:
  file:
    # 日志文件路径
    name: /var/log/api-gateway/app.log
  level:
    # 根日志级别
    root: INFO