spring:
  application:
    name: FeignCloudClientApplication
eureka:
  client:
    service-url:
      defaultZone: http://192.168.141.128:1111/eureka/,http://192.168.141.128:2222/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

feign:
  client:
    config:
      UserService:
        connectTimeout: 5000
        readTimeout: 5000
