server:
  port: 3333
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://192.168.141.128:3306/microservice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: linkout_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5
      max-active: 25
      max-idle: 10
      min-idle: 5
      max-wait-millis: 10000
      validation-query: SELECT 1
      connection-properties: characterEncoding=utf8
  application:
    name: auth_server

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      baorant:
        auth_server: DEBUG
    root: INFO