# ConfigServerGit 配置文件 (dev环境)
# 此文件应放置在Git仓库的config目录下
# 当ConfigClient启动时会从配置服务器获取此文件中的配置

server:
  port: 8088
  
# 自定义数据配置
# 这个配置会被ConfigClient通过GitConfig类读取
# 如果ConfigClient显示env为null，检查此属性是否存在
data:
  env: git-dev-fixed

# 问题排查提示：
# 1. 确保此文件位于Git仓库的config目录下
# 2. 确保文件名格式为 {application}-{profile}.yml，其中application来自ConfigClient的spring.application.name
# 3. 确保ConfigServerGit能正确访问Git仓库
# 4. 修改此文件后需要刷新ConfigClient才能获取最新配置