spring:
  application:
    name: RibbonHelloApplication
eureka:
  client:
    service-url:
      defaultZone: http://192.168.159.128:1111/eureka/,http://192.168.159.128:2222/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}