spring:
  application:
    name: feign-client

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://192.168.141.128:1111/eureka/,http://192.168.141.128:2222/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}

feign:
  client:
    config:
      userservice:
        connectTimeout: 5000
        readTimeout: 5000

