package com.baorant.auth_server.dao;

import com.baorant.auth_server.entity.SpringcloudUserRole;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SpringcloudUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user_role
     *
     * @mbg.generated
     */
    int insert(SpringcloudUserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user_role
     *
     * @mbg.generated
     */
    int insertSelective(SpringcloudUserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user_role
     *
     * @mbg.generated
     */
    SpringcloudUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpringcloudUserRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpringcloudUserRole row);
}