package com.baorant.auth_server.dao;

import com.baorant.auth_server.entity.SpringcloudUser;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SpringcloudUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user
     *
     * @mbg.generated
     */
    int insert(SpringcloudUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user
     *
     * @mbg.generated
     */
    int insertSelective(SpringcloudUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user
     *
     * @mbg.generated
     */
    SpringcloudUser selectByPrimaryKey(Integer id);

    SpringcloudUser findByUsername(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpringcloudUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table springcloud_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpringcloudUser row);
}